theme: jekyll-theme-slate

title: HeRo 2.0: A Low-Cost Robot for Swarm Robotics Research

author: Paulo Rezeck

description: The design of a novel platform for swarm robotics applications that is low cost, easy to assemble using off-the-shelf components, and deeply integrated with the most used robotic framework available today: ROS (Robot Operating System). The robotic platform is entirely open, composed of a 3D printed body and open-source software.


